### ISSUE TITLE
How to obtain individual user's webhook URL for config via User model DB

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel-notification-channels/microsoft-teams#21]
Hi, I've just been browsing the Microsoft Teams notification channel. In my web application, users have the option to intgrate Microsoft Teams to receive notifications, by design, each user in my system needs their own webhook URL, but the assumption of this channel is that only one Microsoft Teams account will be set up and used as the [config](https://laravel-notification-channels.com/microsoft-teams/#installation) doesn't seem to mention anything about pulling from the DB.

How can I obtain the user's webhook URL that they desire in my `User` model?

**Comment by Tob0t** [comment]
Hi Ryan,
this should be quite easily solvable since Microsoft Teams is just a notification like any other.
You can e.g create a method on your `User` model to get the correct webhook link from your database.
In the documentation, you can find it under https://laravel-notification-channels.com/microsoft-teams/#usage with the method  `routeNotificationForMicrosoftTeams`. Instead of referring to a static config value, you can refer to a dynamic value from the `User` model.

Another alternative is by just packing it directly to the `$notifiable` object and then reading it out from there
```
public function toMicrosoftTeams($notifiable)
    {
        return MicrosoftTeamsMessage::create()
            ->to($notifiable->teams_webhook_url)
            ...
    }
```
I hope that helped you!

**Comment by Tob0t** [comment]
Closed issue because of inactivity
